language: cpp
sudo: required
dist: trusty

before_install:
- sudo apt-get install -y libgtest-dev

install: sudo apt-get install -y libboost-all-dev
  
compiler:
  - gcc
  
addons:
  apt:
    sources:
      # add PPAs with more up-to-date toolchains
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
      - gcc-5
      - g++-5
      - clang-3.6

script: 
  - cmake . && make && ./test/livecoding-phonebook-test  
