language: cpp
sudo: required
dist: trusty

install: libgtest-dev tinyxml2 libboost-all-dev

compiler:
  - gcc

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.6

script: 
  - cmake . && make && ./unitTest  
